server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # SPA용: 없는 파일은 index.html로
    location / {
        try_files $uri /index.html;
    }

    # static 파일 처리
    location /assets/ {
        try_files $uri =404;
    }

    location /img/ {
        try_files $uri =404;
    }
}